FROM tallos/nodejs:14.16.3 as build

WORKDIR /home/front

COPY package.*json ./

RUN npm install

COPY . .

RUN npm run build

FROM tallos/nodejs:14.16.3

LABEL maintaner="front"

WORKDIR /home/front

COPY --from=build /home/front/dist ./dist
COPY --from=build /home/front/node_modules ./node_modules

RUN npm install -g serve

USER node

EXPOSE 8092

ENTRYPOINT [ "serve", "-s", "dist", "-l", "8092" ]